services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    expose:
      - 3000
    # volumes:
    #   - ./customer-microservice/src:/usr/src/app/src
    # command: npm run start:dev
    command: tail -f /dev/null

  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3.12.14-management-alpine'
    # hostname: my-rabbitmq
    environment:
      RABBITMQ_DEFAULT_PASS: 'admin'
      RABBITMQ_DEFAULT_USER: 'admin'
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
